### ISSUE TITLE
Sending video message support?

### ISSUE THREAD

**Issue by huyduc** [layerhq/Atlas-Messenger-iOS#190]
Hi, 
We're trying to create a chat application with capability to send video file. We're currently experiencing this crash.

![screenshot 2015-07-01 12 48 07](https://cloud.githubusercontent.com/assets/721399/8450029/590a4aba-2009-11e5-87bc-161a9ff787d4.png)

We create the attachment using this ATLMediaAttachment class method

```objective-c
+ (instancetype)mediaAttachmentWithAssetURL:(NSURL *)assetURL thumbnailSize:(NSUInteger)thumbnailSize;
```

I suspect it's due to the way mediaInputStream was created (probably not support video or something)

```objective-c
self.mediaInputStream = [ATLMediaInputStream mediaInputStreamWithAssetURL:asset.defaultRepresentation.url];
```

If I create the message this way, it's sent successfully without crashing

```objective-c
        ALAssetRepresentation *rep = [asset defaultRepresentation];
        Byte *buffer = (Byte*)malloc(rep.size);
        NSUInteger buffered = [rep getBytes:buffer fromOffset:0.0 length:rep.size error:&error];
        NSData *theData = [NSData dataWithBytesNoCopy:buffer length:buffered freeWhenDone:YES];
        LYRMessagePart *messagePart = [LYRMessagePart messagePartWithMIMEType:@"video/quicktime" stream:[NSInputStream inputStreamWithData:theData]];
        NSError *theError;
        LYRMessage *message = [self.layerClient newMessageWithParts:@[messagePart] options:nil error:&theError];
        BOOL success = [self.conversation sendMessage:message error:&theError];
```

Could somebody point me to the direction on how to send video message using ATLMediaInputStream?
Thanks !

**Comment by khanhvu161188** [comment]
I use another way for sending video, 

`
NSURL *filePath = info[UIImagePickerControllerMediaURL];
NSInputStream *stream = [[NSInputStream alloc] initWithURL:filePath];
LYRMessagePart *videoPart = [LYRMessagePart messagePartWithMIMEType:@"video/mov" stream:stream];
NSError *error;
LYRMessage *message = [self.layerClient newMessageWithParts:@[videoPart] options:nil error:&error];
BOOL success = [self.conversation sendMessage:message error:&error];
if (!success) {
NSLog(@"Failed Sending Message with error: %@", error);
}
}`


i can see that 1 file has been downloaded at receiver side, but the problem is i cannot render this file as normal video. This file is saved without extension, i can see photo can work with file without extension but i meet hard with video in this case. So please help us resolve them @kcoleman731

**Comment by kmahal** [comment]
Atlas now supports video messaging by default.
