### ISSUE TITLE
Performance is too poor

### ISSUE THREAD

**Issue by khanhvuNOIS** [layerhq/Atlas-Messenger-iOS#202]
@chipxsd  @kcoleman731 @blakewatters @kmahal @maju6406 
Hi Atlas team, I've used Atlas from beginning of my project but at this time, i feel Atlas is too bad in performance so that we cannot use it in production app. I've though my code gave problem but after checkout sample from this repository, i even cannot type in 1 group conversation that have 3 participants. If there's 1 use typing or try to spam me from 1 to 10  ( 1, 2, 3, 4, 5, 6, 7, 8, 9, 10). I even cannot type on my input toolbar control here. 
Please diving deep in performance if we want to level up Layer and Atlas as strongest realtime platform.
Some UI library is awesome and i'm trying to combine it with Layer than using Atlas now. Forgive me but i cannot use Atlas any more while it's too lag like current.

**Comment by bradytate** [comment]
@khanhvuNOIS Good luck. You will not find a better solution for iOS that works well with Layer out of the box. Atlas is the obvious and best choice. Layer is still an early stage company which brings early stage issues. This is the repo for the example app, so hopefully you are not trying to use this code as it is only an example and not meant to be copied into your project. If that is the case that may be the root of your problems. I may not fully understand your issue(s), however, as your grammar is too poor. Keep up the good work Layer. (Disclaimer: I do not work for Layer).

**Comment by khanhvuNOIS** [comment]
@bradytate i don't care you work or didn't work for Layer!I open an issue here so that Layer team can upgrade their code quality! Atlas is just an UI kit built for Layer and you shouldn't say 'blah blah blah, only atlas is good for Layer'! We work and we meet issue from Atlas library itself not from their sample code like this repository! @Layer team, test performance carefully and fix from now or you skip it and rework all in furure

**Comment by kmahal** [comment]
@bradytate The Layer Team appreciates your support and kind words :)

@khanhvuNOIS we're always looking to improve Atlas to make it the best and fastest solution for Layer customers.  Part of our decision to open source Atlas was to allow the great community of Layer developers to improve and iterate on features at a rate we never could internally.  We'll certainly take a look at this issue internally as it's not an ideal experience and we strive for the best.  However this is also a reminder that Atlas is open sourced so that if developers, like yourself, finds a problem, they can also implement a fix and a pull request to improve the experience for the entire Atlas user base.  Demanding action without any input or solutions is not a beneficial approach to open source development, but working together we can build something great.

I'm going to close out this issue here, and have opened the specific issue mentioned on the Atlas repo here: https://github.com/layerhq/Atlas-iOS/issues/988.
